title: Píratar
description: Vefsíða Pírata
baseurl:
sass:
  sass_dir: _scss
  style: compressed
collections:
  representatives:
    output: true
    permalink: /fulltruar/:categories/
  articles:
    output: true
    permalink: /fulltruar/:categories/:title/
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
