title: Píratar
description: Vefsíða Pírata
baseurl:
sass:
  sass_dir: _scss
  style: compressed
include: ["_pages-en", _pages-is, _pages-pl]
collections:
  pages-en:
    output: true
    permalink: /en/:path
  pages-is:
    output: true
    permalink: /:path
  pages-pl:
    output: true
    permalink: /pl/:path
  articles:
    output: true
    permalink: /folkid/greinar/:path/
  administration:
    output: true
  associations:
    output: true
  external-articles:
    output: false
  people:
    output: false
defaults:
  -
    scope:
      path: "_pages-is"
    values:
      lang: is
      layout: page
  -
    scope:
      path: "_pages-en"
    values:
      lang: en
      layout: page
  -
    scope:
      path: _pages-pl
    values:
      lang: pl
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      banner: true
      lang: is
  -
    scope:
      path: ""
      type: articles
    values:
      banner: true
      lang: is
  -
    scope:
      path: "_associations"
    values:
      layout: association
      lang: is
      banner: true
      permalink: /adildarfelog/:title/
  -
    scope:
      path: "_associations/en"
    values:
      permalink: /en/assoications/:title/
      lang: en
      layout: association
facebook:
  app_id: 2425179654215087
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
